### ISSUE TITLE
Messenger Code API

### ISSUE THREAD

**Issue by ansarizafar** [botmasterai/botmaster-messenger#2]
Thanks for all the hard work and publishing V3.  Above mentioned feature would also be a useful addition. Messenger Code API can also be used for this use case [Support handling Multiple Facebook pages](https://github.com/howdyai/botkit/pull/259)

**Comment by jdwuarin** [comment]
No worries. Because of how Botmaster works, supporting multiple Facebook pages already works out of the box. All you need to do is create multiple messenger bot instances with multiple credentials and then add them to your botmaster instance. When you get an update, you can then answer from a different bot simply by using botmaster.getBot if you are so inclined. And thus, have your your user swap the bot they are talking with. I'll close this issue for now. If it's unclear however, or something else should be added, please reopen it.
